[[mgr.prepend_keymap]]
desc = "将文件内容复制到剪贴板"
on = "Y"
run = ["shell 'cat \"$@\" | pbcopy'"]

[[mgr.prepend_keymap]]
desc = "Chmod on selected files"
on = ["c", "m"]
run = "plugin chmod"

[[mgr.prepend_keymap]]
desc = "Compress with ouch"
on = ["C"]
run = "plugin ouch"
