# yazi.toml
[mgr]
show_hidden = true
ratio       = [ 1, 3, 3 ]
sort_by     = "natural"
linemode    = "size"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
