# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
# Super + hjkl：切换焦点窗口
bind=SUPER,h,movefocus,l
bind=SUPER,l,movefocus,r
bind=SUPER,j,movefocus,u
bind=SUPER,k,movefocus,d

# Super + Shift + hjkl：移动窗口
bind=SUPERSHIFT,h,movewindow,l
bind=SUPERSHIFT,l,movewindow,r
bind=SUPERSHIFT,j,movewindow,u
bind=SUPERSHIFT,k,movewindow,d

# Super + R：切换到RESIZE模式
bind=SUPER,R,submap,resize
submap=resize
    # 在RESIZE模式下使用hjkl调整窗口大小
    binde=,h,resizeactive,-10 0
    binde=,l,resizeactive,10 0
    binde=,k,resizeactive,0 -10
    binde=,j,resizeactive,0 10
    # ESC退出RESIZE模式
    bind=,escape,submap,reset
submap=reset

# Super + PrtSc 截屏
bind = SUPERSHIFT, PRINT, exec, hyprshot -m region

# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
# cursor {
#     no_hardware_cursors = false
# }

# Blur for waybar
#layerrule = blur, waybar

exec-once=fcitx5
exec-once=clash-verge
exec-once=thunderbird

